# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tflock < Formula
  desc "Lock Terraform state manually"
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kerraform/tflock/releases/tag/v0.0.1", :using => CurlDownloadStrategy
      sha256 "f994849250613690d2ea40f1957ef695fb289342266412fdf5427fa1f57fc7f7"

      def install
        bin.install "tflock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kerraform/tflock/releases/tag/v0.0.1", :using => CurlDownloadStrategy
      sha256 "e47f5f4448f0436415eec2acda6ff8e6d24af133cbb310d1dc15dc9343f6f097"

      def install
        bin.install "tflock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerraform/tflock/releases/tag/v0.0.1", :using => CurlDownloadStrategy
      sha256 "7e3c32b8a15f844b547baeef31185175c55df7be5cc251097f367300e76c6b7e"

      def install
        bin.install "tflock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kerraform/tflock/releases/tag/v0.0.1", :using => CurlDownloadStrategy
      sha256 "9d95ba94a4193564d7f3203957e7e1359b4146a670603ce09467c4d6a2a84c69"

      def install
        bin.install "tflock"
      end
    end
  end
end
