# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tflock < Formula
  desc "Lock Terraform state manually"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kerraform/tflock/releases/download/v0.1.0/tflock_0.1.0_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "beb41aeff882c09d1a45f3083c278b09c76b3924aab31b91fc49182923cb5451"

      def install
        bin.install "tflock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kerraform/tflock/releases/download/v0.1.0/tflock_0.1.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "03646d45533f2559d6ff012a7e366b103cd6e2cdc8d0b075f902df9d91f70b87"

      def install
        bin.install "tflock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerraform/tflock/releases/download/v0.1.0/tflock_0.1.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "28a05f0439d1a3ccea86601fbd177523d73ec094fa89a91a1f2000bfbaa5ec14"

      def install
        bin.install "tflock"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kerraform/tflock/releases/download/v0.1.0/tflock_0.1.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d802b430333b3779044452f0ab1248d9bffed8eb1eb0c4323e884a37550e7c20"

      def install
        bin.install "tflock"
      end
    end
  end
end
